# Generated by Django 5.1.3 on 2024-11-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='side',
            new_name='order_side',
        ),
    ]
