# Generated by Django 5.1.3 on 2024-11-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20241127_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricealert',
            old_name='condition',
            new_name='alert_type',
        ),
    ]
