# Generated by Django 5.1.3 on 2024-11-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20241127_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount_usd',
            new_name='amount',
        ),
    ]
