# Generated by Django 5.1.3 on 2024-11-28 11:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_userprofile_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('symbol', 'asset_type')},
        ),
        migrations.RemoveField(
            model_name='order',
            name='executed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_side',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='price_threshold',
        ),
        migrations.RemoveField(
            model_name='pricealert',
            name='triggered_at',
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='forex_base_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='asset',
            name='forex_quote_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='stock_exchange',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='filled_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='trailing_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='percentage_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='price_target',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='rsi_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('expired', 'Expired')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='volume_target',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.asset'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop_loss', 'Stop Loss'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='alert_type',
            field=models.CharField(choices=[('price_above', 'Price Above'), ('price_below', 'Price Below'), ('price_change_pct', 'Price Change %'), ('volume_above', 'Volume Above'), ('rsi_above', 'RSI Above'), ('rsi_below', 'RSI Below')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.asset'),
        ),
        migrations.DeleteModel(
            name='TradingBot',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_updated',
        ),
    ]
