# Generated by Django 5.1.3 on 2024-11-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_asset_unique_together_remove_order_executed_at_and_more'),
    ]

    operations = [
    ]
