# Generated by Django 5.1.3 on 2024-11-28 20:09

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_portfoliosnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='base_currency',
            field=models.CharField(blank=True, max_length=3, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='quote_currency',
            field=models.CharField(blank=True, max_length=3, default=''),
            preserve_default=False,
        ),
    ]
