# Generated by Django 5.1.3 on 2024-11-28 20:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_auto_20241128_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, max_length=100, default=''),
            preserve_default=False,
        ),
    ]
