# Generated by Django 5.1.3 on 2024-11-28 20:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_auto_20241128_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.DecimalField(max_digits=20, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(max_digits=20, decimal_places=8, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_24h',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_percentage_24h',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume_24h',
            field=models.DecimalField(max_digits=20, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='high_24h',
            field=models.DecimalField(max_digits=20, decimal_places=8, default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_24h',
            field=models.DecimalField(max_digits=20, decimal_places=8, default=0),
        ),
    ]
