# Generated by Django 5.1.3 on 2024-11-28 20:40

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20241128_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
