# Generated by Django 5.1.3 on 2024-12-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_alter_userprofile_phone_number'),
    ]

    operations = [
    ]
