# Generated by Django 5.1.3 on 2024-12-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_market_data_feed'),
    ]

    operations = [
    ]
